export default [
    {name: "Year", edit: true, field: "year", jsonExport: true},
    {name: "Move Link", edit: false, field: "movie_link", jsonExport: false},
    {name: "Album", edit: true, field: "album", jsonExport: true},
    {name: "Lyrics Link", edit: false, field: "lyrics_link", jsonExport: false},
    {name: "Song Name", edit: true, field: "song_name", jsonExport: true},
    {name: "Lyricist", edit: true, field: "lyricist", jsonExport: true},
    {name: "Singers", edit: true, field: "singers", jsonExport: true},
    {name: "Composer", edit: true, field: "composer", jsonExport: true},
    {name: "Lyrics", edit: false, field: "lyrics", jsonExport: true},
    {name: "Metaphor 1", edit: false, field: "metaphor_1", jsonExport: false},
    {name: "Metaphor 1 Meaning", edit: false, field: "metaphor_1_meaning", jsonExport: false},
    {name: "Metaphor 1 Source", edit: false, field: "metaphor_1_source", jsonExport: false},
    {name: "Metaphor 1 Target", edit: false, field: "metaphor_1_target", jsonExport: false},
    {name: "Metaphor 1 Interpretation", edit: false, field: "metaphor_1_interpretation", jsonExport: false},
    {name: "Metaphor 2", edit: false, field: "metaphor_2", jsonExport: false},
    {name: "Metaphor 2 Meaning", edit: false, field: "metaphor_2_meaning", jsonExport: false},
    {name: "Metaphor 2 Source", edit: false, field: "metaphor_2_source", jsonExport: false},
    {name: "Metaphor 2 Target", edit: false, field: "metaphor_2_target", jsonExport: false},
    {name: "Metaphor 2 Interpretation", edit: false, field: "metaphor_2_interpretation", jsonExport: false},
    {name: "Metaphor 3", edit: false, field: "metaphor_3", jsonExport: false},
    {name: "Metaphor 3 Meaning", edit: false, field: "metaphor_3_meaning", jsonExport: false},
    {name: "Metaphor 3 Source", edit: false, field: "metaphor_3_source", jsonExport: false},
    {name: "Metaphor 3 Target", edit: false, field: "metaphor_3_target", jsonExport: false},
    {name: "Metaphor 3 Interpretation", edit: false, field: "metaphor_3_interpretation", jsonExport: false},
    {name: "Metaphor 4", edit: false, field: "metaphor_4", jsonExport: false},
    {name: "Metaphor 4 Meaning", edit: false, field: "metaphor_4_meaning", jsonExport: false},
    {name: "Metaphor 4 Source", edit: false, field: "metaphor_4_source", jsonExport: false},
    {name: "Metaphor 4 Target", edit: false, field: "metaphor_4_target", jsonExport: false},
    {name: "Metaphor 4 Interpretation", edit: false, field: "metaphor_4_interpretation", jsonExport: false},
    {name: "Metaphor 5", edit: false, field: "metaphor_5", jsonExport: false},
    {name: "Metaphor 5 Meaning", edit: false, field: "metaphor_5_meaning", jsonExport: false},
    {name: "Metaphor 5 Source", edit: false, field: "metaphor_5_source", jsonExport: false},
    {name: "Metaphor 5 Target", edit: false, field: "metaphor_5_target", jsonExport: false},
    {name: "Metaphor 5 Interpretation", edit: false, field: "metaphor_5_interpretation", jsonExport: false},
]