export default [
    {name: "Year", edit: true, field: "year"},
    {name: "Move Link", edit: false, field: "movie_link"},
    {name: "Album", edit: true, field: "album"},
    {name: "Lyrics Link", edit: false, field: "lyrics_link"},
    {name: "Song Name", edit: true, field: "song_name"},
    {name: "Lyricist", edit: true, field: "lyricist"},
    {name: "Singers", edit: true, field: "singers"},
    {name: "Composer", edit: true, field: "composer"},
    {name: "Lyrics", edit: false, field: "lyrics"},
    {name: "Metaphor 1", edit: false, field: "metaphor_1"},
    {name: "Metaphor 1 Meaning", edit: false, field: "metaphor_1_meaning"},
    {name: "Metaphor 2", edit: false, field: "metaphor_2"},
    {name: "Metaphor 2 Meaning", edit: false, field: "metaphor_2_meaning"},
    {name: "Metaphor 3", edit: false, field: "metaphor_3"},
    {name: "Metaphor 3 Meaning", edit: false, field: "metaphor_3_meaning"},
    {name: "Metaphor 4", edit: false, field: "metaphor_4"},
    {name: "Metaphor 4 Meaning", edit: false, field: "metaphor_4_meaning"},
    {name: "Metaphor 5", edit: false, field: "metaphor_5"},
    {name: "Metaphor 5 Meaning", edit: false, field: "metaphor_5_meaning"},
]