export default [
    {name: "Year", edit: true, field: "year"},
    {name: "Move Link", edit: false, field: "movie_link"},
    {name: "Album", edit: true, field: "album"},
    {name: "Lyrics Link", edit: false, field: "lyrics_link"},
    {name: "Song Name", edit: true, field: "song_name"},
    {name: "Lyricist", edit: true, field: "lyricist"},
    {name: "Singers", edit: true, field: "singers"},
    {name: "Composer", edit: true, field: "composer"},
    {name: "Lyrics", edit: false, field: "lyrics"},
    {name: "Metaphor 1", edit: false, field: "metaphor_1"},
    {name: "Metaphor 1 Source", edit: false, field: "metaphor_1_source"},
    {name: "Metaphor 1 Target", edit: false, field: "metaphor_1_target"},
    {name: "Metaphor 1 Interpretation", edit: false, field: "metaphor_1_interpretation"},
    {name: "Metaphor 2", edit: false, field: "metaphor_2"},
    {name: "Metaphor 2 Source", edit: false, field: "metaphor_2_source"},
    {name: "Metaphor 2 Target", edit: false, field: "metaphor_2_target"},
    {name: "Metaphor 2 Interpretation", edit: false, field: "metaphor_2_interpretation"},
    {name: "Metaphor 3", edit: false, field: "metaphor_3"},
    {name: "Metaphor 3 Source", edit: false, field: "metaphor_3_source"},
    {name: "Metaphor 3 Target", edit: false, field: "metaphor_3_target"},
    {name: "Metaphor 3 Interpretation", edit: false, field: "metaphor_3_interpretation"},
    {name: "Metaphor 4", edit: false, field: "metaphor_4"},
    {name: "Metaphor 4 Source", edit: false, field: "metaphor_4_source"},
    {name: "Metaphor 4 Target", edit: false, field: "metaphor_4_target"},
    {name: "Metaphor 4 Interpretation", edit: false, field: "metaphor_4_interpretation"},
    {name: "Metaphor 5", edit: false, field: "metaphor_5"},
    {name: "Metaphor 5 Source", edit: false, field: "metaphor_5_source"},
    {name: "Metaphor 5 Target", edit: false, field: "metaphor_5_target"},
    {name: "Metaphor 5 Interpretation", edit: false, field: "metaphor_5_interpretation"},
]